
package com.ysmall.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.9
 * 2016-03-29T10:29:55.302+08:00
 * Generated source version: 2.5.9
 */

@WebFault(name = "Exception", targetNamespace = "http://service.ysmall.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.ysmall.service.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.ysmall.service.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.ysmall.service.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.ysmall.service.Exception getFaultInfo() {
        return this.exception;
    }
}
